#!/bin/bash

#PBS -N curation_pretext
#PBS -l select=1:ncpus=2:mem=8gb
#PBS -l walltime=08:00:00
#PBS -j oe
#PBS -V

cd $PBS_O_WORKDIR
module load apptainer

nextflow run sanger-tol/curationpretext \
  --input /home/proj_202504p2_BD-MED/abner/durio/assembly/DurGra_Simpur/DurGra_Sim.hifiasm.20260204/scaffolding_hap1/yahs/asm_hap1_scaffolds_final.fa.gz \
  --cram /home/proj_202504p2_BD-MED/abner/durio/raw_data/DurSim  \
  --reads /home/proj_202504p2_BD-MED/abner/durio/raw_data/DurSim \
  --multi_mapping 10 \
  --read_type hifi \
  --map_order length \
  --run_hires false \
  --sample DurGra_Simpur \
  --teloseq TTTAGGG \
  --outdir curation \
  -profile singularity